#
###################################
# Site wide configuration
####################################
#
title: mcjohn.lv
email: mcjohn@inbox.lv
description: A simple blog about frontend programming.
url: https://mcjohn.lv # the base hostname & protocol for your site
keywords: ["Programming", "Frontend", "Javascript", "HTML5", "CSS3"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jānis Konutis
  avatar: mcjohn-photo.jpg
  job: "Frontend Developer"
  bio: "WPBakery, Latvia."
  email: mcjohn@inbox.lv
  disqus-shortname: mcjohnblog
  twitter: #username
  facebook: janis.konutis #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: konutis #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: janiskonutis #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
